<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.umar</groupId>
        <artifactId>salon-microservice</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>business</artifactId>

    <packaging>pom</packaging>

    <modules>
        <module>user-service</module>
        <module>category-service</module>
        <module>payment-service</module>
        <module>salon-service</module>
        <module>service-offering</module>
        <module>booking-service</module>
        <module>review-service</module>
        <module>notification-service</module>
        <module>ai-recommendation-service</module>
        <module>ai-assistant-service</module>
    </modules>

</project>
